# Assignment 3

# Q1.)

In [14]:
import numpy as np

In [2]:
arr = np.arange(2,51,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Q2.)

In [24]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
numpylist1 = np.asarray(list1,dtype =np.float32)
numpylist2 = np.asarray(list2,dtype = np.float32)
numpylist = np.concatenate([numpylist1,numpylist2])
print(numpylist)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


# Q3.)

In [41]:
arr = np.array( [[1,2,3] , [4,5,6]] )
print(np.ndim(arr))
print(np.size(arr))

2
6


# Q4.)

In [49]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("1D Numpy Array:",arr)
arr2 = np.reshape(arr,(2,5))
print(arr2)
arr3 = arr[ :, np.newaxis]
print(arr3)

1D Numpy Array: [ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


# Q5.)

In [64]:
array1 = np.arange(2,11,2)
print(array1)
array2 = np.arange(3,19,3)
print(array2)
vert = np.vstack(array1)
hori = np.hstack(array2)
print(vert)
print("Horizontal stack",hori)

[ 2  4  6  8 10]
[ 3  6  9 12 15 18]
[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]]
Horizontal stack [ 3  6  9 12 15 18]


# Q6.)

In [73]:
numbers = [1,2,2,3,4,5]
unique_numbers = list(set(numbers))
print(unique_numbers)
countunique = len(set(numbers))
print(countunique)

[1, 2, 3, 4, 5]
5
